version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "github-actions"
      prefix-development: "github-actions dev"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pip production"
      prefix-development: "pip development"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "docker"
      prefix-development: "docker development"