services:
  bot:
    container_name: garminworkouts-bot
    build:
      context: ./
    environment:
      GARMIN_USERNAME: ${GARMIN_USERNAME}
      GARMIN_PASSWORD: ${GARMIN_PASSWORD}
      vV02: ${vV02}
      fmin: ${fmin}
      rfmax: ${rfmax}
      rflt: ${rflt}
      rFTP: ${rFTP}
      cfmax: ${cfmax}
      cflt: ${cflt}
      cFTP: ${cFTP}
      sfmax: ${sfmax}
      sflt: ${sflt}
      BOT_TOKEN: ${BOT_TOKEN}
      VOLUME: ${VOLUME}
    volumes:
      - ${VOLUME}/events:/usr/src/app/events
      - ${VOLUME}/garminconnect:/usr/src/app/garminconnect