version: '3'

services:
  bot:
    container_name: garminworkouts-bot
    build:
      context: ./
      args:
        GARMIN_USERNAME: ${GARMIN_USERNAME}
        GARMIN_PASSWORD: ${GARMIN_PASSWORD}
        vV02: ${vV02}
        fmin: ${fmin}
        fmax: ${fmax}
        rFTP: ${rFTP}
        cFTP: ${cFTP}
        BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - ./events:/usr/src/app/events
      - ./events/planning:/usr/src/app/events/planning