name: CI

on:
  push:
    paths:
      - 'garminworkouts/**'
      - 'tests/**'
  pull_request_target:
    paths:
      - 'garminworkouts/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: flake8 garminworkouts tests

  build:
    runs-on: ubuntu-latest
    needs: [lint]

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
      GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      vV02: ${{ secrets.vV02 }}
      fmin: ${{ secrets.fmin }}
      fmax: ${{ secrets.fmax }}
      flt: ${{ secrets.flt }}
      rFTP: ${{ secrets.rFTP }}
      cFTP: ${{ secrets.cFTP }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    permissions:
      actions: read
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: pytest --cov=garminworkouts --cov-report=xml --ignore=garminworkouts/__main__.py tests
      - uses: codecov/codecov-action@v4.5.0
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:          
          env_vars: PYTHON_VERSION
          flags: unittests
          verbose: true

  result:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: |
          result="${{ needs.build.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
