name: CI

on:
  push:
  pull_request_target:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: flake8 garminworkouts tests

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      USERNAME: ${{ secrets.GARMIN_USERNAME }}
      PASSWORD: ${{ secrets. PASSWORD }}
      vV02: ${{ secrets.vV02 }}
      fmin: ${{ secrets.fmin }}
      fmax: ${{ secrets.fmax }}
      rFTP: ${{ secrets.rFTP }}
      cFTP: ${{ secrets.cFTP }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: pytest --cov=garminworkouts --cov-report=xml tests
      - uses: codecov/codecov-action@v3
        with:
          env_vars: PYTHON_VERSION, USERNAME, PASSWORD, vVO2, fmin, fmax, rFTP, cFTP, BOT_TOKEN

  required-checks:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - run: exit 0
