name: CI

on:
  push:
    paths:
      - 'garminworkouts/**'
      - 'tests/**'
  pull_request_target:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: flake8 garminworkouts tests

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
      GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      vV02: ${{ secrets.vV02 }}
      fmin: ${{ secrets.fmin }}
      fmax: ${{ secrets.fmax }}
      flt: ${{ secrets.flt }}
      rFTP: ${{ secrets.rFTP }}
      cFTP: ${{ secrets.cFTP }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    permissions:
      actions: read
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: pytest --cov=garminworkouts --cov-report=xml tests
      - uses: codecov/codecov-action@v3
        with:
          env_vars: PYTHON_VERSION
          flags: unittests
          verbose: true
      - name: 🐛 Debug
        uses: stateful/vscode-server-action@v1
        if: failure()
        with:
          machineName: myMachine # optional, default: GitHub workflow run ID
          timeout: '30000'       # optional, default: 30000

  required-checks:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - run: exit 0
