name: Garmin update

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  
jobs:
  garmin-update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: python -m garminworkouts garmin-update

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Bump Garmin version
