name: "Garmin update"

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour

env:
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  vV02: ${{ secrets.vV02 }}
  fmin: ${{ secrets.fmin }}
  fmax: ${{ secrets.fmax }}
  flt: ${{ secrets.flt }}
  rFTP: ${{ secrets.rFTP }}
  cFTP: ${{ secrets.cFTP }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  
jobs:
  garmin-update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }}
      - uses: ./.github/actions/setup
      # Run the Garmin workouts update script
      - run: python -m garminworkouts garmin-update

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
            commit_message: Update Garmin
